package by.kozik.quest.dao;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by Serge on 07.12.2016.
 */
public interface ConnectionUsable {

    public Statement createStatement() throws SQLException;
    public void close() throws SQLException;
    public void closeResources(Statement statement);
    public void commit() throws SQLException;
    public boolean isClosed() throws SQLException;
    public PreparedStatement prepareStatement(String sql) throws SQLException;
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
    public void rollback() throws SQLException;
    public void setAutoCommit(boolean flag) throws SQLException;
}
